name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  # Check if we need a release and determine version bump
  check-release:
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{ steps.version.outputs.should-release }}
      new-version: ${{ steps.version.outputs.new-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version bump
        id: version
        run: |
          # Get current version from Cargo.toml
          current_version=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "Current version: $current_version"

          # Get commits since last tag
          last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$last_tag" ]; then
            echo "No previous tags found, checking all commits"
            commits=$(git log --oneline --pretty=format:"%s")
          else
            echo "Checking commits since $last_tag"
            commits=$(git log ${last_tag}..HEAD --oneline --pretty=format:"%s")
          fi

          # Skip if no new commits
          if [ -z "$commits" ]; then
            echo "No new commits since last tag"
            echo "should-release=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Commits to analyze:"
          echo "$commits"

          # Check for breaking changes, features, or fixes using conventional commits
          if echo "$commits" | grep -qE "(BREAKING CHANGE|!:|^[^:]*!:)"; then
            bump="major"
          elif echo "$commits" | grep -qE "^feat(\([^)]*\))?:"; then
            bump="minor"
          elif echo "$commits" | grep -qE "^fix(\([^)]*\))?:"; then
            bump="patch"
          else
            echo "No conventional commits found that warrant a release"
            echo "should-release=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Calculate new version
          IFS='.' read -r major minor patch <<< "$current_version"
          case $bump in
            major) new_version="$((major + 1)).0.0" ;;
            minor) new_version="$major.$((minor + 1)).0" ;;
            patch) new_version="$major.$minor.$((patch + 1))" ;;
          esac

          echo "should-release=true" >> $GITHUB_OUTPUT
          echo "new-version=$new_version" >> $GITHUB_OUTPUT
          echo "Bump type: $bump"
          echo "New version will be: $new_version"

  # Update version and create release
  release:
    needs: check-release
    if: needs.check-release.outputs.should-release == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install git-cliff
        run: |
          wget https://github.com/orhun/git-cliff/releases/download/v1.4.0/git-cliff-1.4.0-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf git-cliff-1.4.0-x86_64-unknown-linux-gnu.tar.gz
          sudo mv git-cliff-1.4.0/git-cliff /usr/local/bin/

      - name: Update Cargo.toml version
        run: |
          sed -i 's/^version = ".*"/version = "${{ needs.check-release.outputs.new-version }}"/' Cargo.toml

      - name: Generate changelog
        run: |
          git-cliff --tag v${{ needs.check-release.outputs.new-version }} > CHANGELOG.md

      - name: Commit version bump and changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Cargo.toml CHANGELOG.md
          git commit -m "chore(release): prepare for v${{ needs.check-release.outputs.new-version }}"
          git tag v${{ needs.check-release.outputs.new-version }}
          git push origin main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        run: |
          gh release create v${{ needs.check-release.outputs.new-version }} \
            --title "Release v${{ needs.check-release.outputs.new-version }}" \
            --notes-file CHANGELOG.md \
            --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build and release binaries
  build:
    needs: [check-release, release]
    if: needs.check-release.outputs.should-release == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ needs.check-release.outputs.new-version }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/viewyard dist/
          cd dist && tar -czf viewyard-v${{ needs.check-release.outputs.new-version }}-${{ matrix.target }}.tar.gz viewyard

      - name: Upload release asset
        run: |
          gh release upload v${{ needs.check-release.outputs.new-version }} \
            dist/viewyard-v${{ needs.check-release.outputs.new-version }}-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
